### ISSUE TITLE
Resets Tha Application After Returning From Video

### ISSUE THREAD

**Issue by cihancil** [applicaster/rn-youtube-android#11]
Documentation is not compatible with current React Native verison but I managed to get it working.

I can open Youtube activity but when I press back button my react native application restarts.

App returns the initial page. How can I stop react to restart itself?

**Comment by simonvaucher** [comment]
It is not compatible with the "normal" way they propose (using application instead of activity) but it still works when following the "integration with existing apps" guide -> https://facebook.github.io/react-native/docs/integration-with-existing-apps.html . I've pointed this in the README.
In order to catch the back button event, you need to override `public void onBackPressed()` and `public void invokeDefaultOnBackPressed()` in the activity that holds the `ReactRootView`:

```
    @Override
    public void invokeDefaultOnBackPressed() {
        super.onBackPressed();
    }

@Override
    public void onBackPressed() {
        if (reactInstanceManager != null) {
            reactInstanceManager.onBackPressed(); // react native instance is still alive
        } else {
            // do something else, line finish();
        }
    }
```

Please read carefully the section on the activity lifecycle callbacks, it deals specifically with the back button behavior: https://facebook.github.io/react-native/docs/integration-with-existing-apps.html (click on the "Android" platform button on top).

**Comment by simonvaucher** [comment]
Anything else before I close?

**Comment by cihancil** [comment]
Thanks. I will try as you suggested. 

Sure you can close this issue. Thanks
